version: "3.6"

services:
  bootnode:
    image: hyperledger/besu:latest
    restart: "on-failure"
    container_name: node0
    volumes:
      - ./log-config.xml:/node/log-config.toml
      - ./node0/data:/node/data
      - ./genesis.json:/node/genesis.json
      - ./config.toml:/node/config.toml
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/node/config.toml \
        --node-private-key-file=/node/data/key \
        --min-gas-price=4761904761904 ;
    ports:
      - 8545:8545/tcp
      - 30303:30309/tcp
    networks:
      besu-tester:
        ipv4_address: 172.16.239.11

  node1:
    image: hyperledger/besu:latest
    restart: "on-failure"
    container_name: node1
    volumes:
      - ./log-config.xml:/node/log-config.toml
      - ./node1/data:/node/data
      - ./genesis.json:/node/genesis.json
      - ./config.toml:/node/config.toml
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/node/config.toml \
        --node-private-key-file=/node/data/key \
        --min-gas-price=5714285714285 ;
    depends_on:
      - bootnode
    ports:
      - 8546:8545/tcp
      - 30304:30309/tcp
    networks:
      besu-tester:
        ipv4_address: 172.16.239.12

  node2:
    image: hyperledger/besu:latest
    restart: "on-failure"
    container_name: node2
    volumes:
      - ./log-config.xml:/node/log-config.toml
      - ./node2/data:/node/data
      - ./genesis.json:/node/genesis.json
      - ./config.toml:/node/config.toml
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/node/config.toml \
        --node-private-key-file=/node/data/key \
        --min-gas-price=6190476190476 ;
    depends_on:
      - bootnode
    ports:
      - 8547:8545/tcp
      - 30305:30309/tcp
    networks:
      besu-tester:
        ipv4_address: 172.16.239.13

  node3:
    image: hyperledger/besu:latest
    restart: "on-failure"
    container_name: node3
    volumes:
      - ./log-config.xml:/node/log-config.toml
      - ./node3/data:/node/data
      - ./genesis.json:/node/genesis.json
      - ./config.toml:/node/config.toml
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/node/config.toml \
        --node-private-key-file=/node/data/key \
        --min-gas-price=6666666666666 ;
    depends_on:
      - bootnode
    ports:
      - 8548:8545/tcp
      - 30306:30309/tcp
    networks:
      besu-tester:
        ipv4_address: 172.16.239.14

  explorer:
    image: alethio/ethereum-lite-explorer
    environment:
      - APP_NODE_URL=http://localhost:8545
    depends_on:
      - bootnode
    ports:
      - 25000:80/tcp
    networks:
      besu-tester:
        ipv4_address: 172.16.239.15

networks:
  besu-tester:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
          gateway: 172.16.239.1
